export interface StandaloneLab {
  id: string;
  title: string;
  description: string;
  category: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  estimatedMin: number;
  xpReward: number;
  accentColor: string;
  scenario: string;
  tasks: string[];
  labPrompt: string;
  keywords: string[];
  tools?: string[];
  framework?: string;
}

export const STANDALONE_LABS: StandaloneLab[] = [

  // ── PHISHING & SOCIAL ENGINEERING ─────────────────────────────────────────

  {
    id: 'lab-phish-email-analysis',
    title: 'Analyze a Spear Phishing Email',
    description: 'Dissect a realistic spear phishing email and identify every deceptive element.',
    category: 'Phishing & Social Engineering',
    difficulty: 'beginner',
    estimatedMin: 20,
    xpReward: 120,
    accentColor: '#00ff41',
    scenario: 'You receive an email appearing to be from your CEO asking you to urgently wire $48,000 to a new vendor. The email mentions a specific internal project name, uses the CEO\'s correct title, and includes a PDF attachment called "Wire_Instructions_Confidential.pdf".',
    tasks: ['Identify all social engineering triggers in the email', 'List the technical indicators you would check (email headers, sender domain, links)', 'Describe how to verify the request through a separate communication channel', 'Write the security awareness reminder you would send to all employees after this incident'],
    labPrompt: 'You received a suspicious BEC (Business Email Compromise) email impersonating your CEO requesting an urgent wire transfer. Analyze the social engineering tactics used, identify all technical and behavioral red flags, explain how you verify the request safely, and draft the employee awareness communication.',
    keywords: ['BEC', 'wire transfer', 'social engineering', 'email header', 'sender verification', 'urgency', 'pretexting', 'out-of-band verification'],
    tools: ['Email header analyzer', 'WHOIS', 'MX Toolbox'],
    framework: 'NIST CSF',
  },

  {
    id: 'lab-vishing-defense',
    title: 'Defend Against Vishing Attacks',
    description: 'Build a response playbook for voice phishing attacks targeting your help desk.',
    category: 'Phishing & Social Engineering',
    difficulty: 'intermediate',
    estimatedMin: 25,
    xpReward: 140,
    accentColor: '#00ff41',
    scenario: 'Your IT help desk receives a call from someone claiming to be the VP of Finance, saying they are traveling internationally and locked out of their account. They are demanding an immediate password reset, claim they cannot wait, and say the CEO has approved it verbally.',
    tasks: ['Identify all manipulation techniques used by the caller', 'Write the identity verification procedure the help desk must follow', 'Describe what the help desk should do if the caller refuses to verify identity', 'Create a one-page vishing response card for help desk staff'],
    labPrompt: 'Your help desk is targeted by a vishing call using authority, urgency, and pressure tactics. Describe the complete response: identify the social engineering techniques, define your mandatory identity verification procedure, explain what to do when a caller refuses to verify, and write a vishing defense procedure card for your team.',
    keywords: ['vishing', 'help desk', 'identity verification', 'authority', 'urgency', 'password reset', 'social engineering', 'callback verification'],
    tools: ['Ticketing system', 'Call recording'],
    framework: 'CIS Control 14',
  },

  {
    id: 'lab-pretexting-awareness',
    title: 'Build a Pretexting Awareness Campaign',
    description: 'Design a security awareness campaign targeting pretexting and social engineering vectors.',
    category: 'Phishing & Social Engineering',
    difficulty: 'beginner',
    estimatedMin: 30,
    xpReward: 130,
    accentColor: '#00ff41',
    scenario: 'Your organization has experienced three pretexting incidents in the past quarter: an attacker posing as an IT vendor gained server room access, another impersonated HR to obtain employee personal information, and a third called the CFO\'s assistant pretending to be an auditor.',
    tasks: ['Categorize each incident by pretexting technique', 'Identify which department and process failed each time', 'Design a 3-module security awareness training addressing these vectors', 'Write the metrics you would use to measure campaign effectiveness'],
    labPrompt: 'Three pretexting attacks succeeded against your organization using different impersonation scenarios. Analyze each incident, identify the process failures, design a security awareness campaign to address the gaps, and define measurable success metrics.',
    keywords: ['pretexting', 'physical security', 'HR data', 'vendor impersonation', 'security awareness', 'training metrics', 'access control', 'process failure'],
    framework: 'NIST SP 800-50',
  },

  {
    id: 'lab-phishing-simulation-design',
    title: 'Design a Phishing Simulation Program',
    description: 'Plan and run an authorized phishing simulation to measure employee susceptibility.',
    category: 'Phishing & Social Engineering',
    difficulty: 'intermediate',
    estimatedMin: 35,
    xpReward: 150,
    accentColor: '#00ff41',
    scenario: 'Your CISO wants to measure phishing susceptibility across 1,000 employees in three departments: Finance, HR, and Engineering. You have 6 weeks to design, run, and report on the simulation.',
    tasks: ['Define the scope, goals, and success criteria for the simulation', 'Design three different phishing templates (one per department) using realistic pretexts', 'Describe how you measure click rate, credential submission, and reporting rate', 'Write the post-simulation report format including remediation recommendations'],
    labPrompt: 'Design a complete phishing simulation program for 1,000 employees across three departments. Define your scope and goals, create three targeted phishing templates, describe your measurement methodology, and write the reporting format including how you handle employees who fail repeatedly.',
    keywords: ['phishing simulation', 'click rate', 'reporting rate', 'credential submission', 'targeted template', 'remediation', 'awareness training', 'simulation metrics'],
    framework: 'SANS Security Awareness',
  },

  // ── NETWORK SECURITY ──────────────────────────────────────────────────────

  {
    id: 'lab-network-recon',
    title: 'Network Reconnaissance & Enumeration',
    description: 'Perform authorized reconnaissance on a test network to understand the attacker\'s view.',
    category: 'Network Security',
    difficulty: 'intermediate',
    estimatedMin: 40,
    xpReward: 160,
    accentColor: '#60a5fa',
    scenario: 'You are a penetration tester conducting authorized reconnaissance on a target network range (10.10.10.0/24). You need to identify live hosts, open services, operating systems, and potential vulnerabilities before presenting findings.',
    tasks: ['Describe the nmap commands to enumerate live hosts, open ports, and service versions', 'Explain how to identify the OS of discovered hosts', 'List at least 5 critical services and the specific vulnerabilities you would look for in each', 'Describe how you would document findings in a reconnaissance report'],
    labPrompt: 'You are performing authorized network reconnaissance on 10.10.10.0/24. Describe your complete recon methodology: host discovery, port scanning, service enumeration, OS fingerprinting, and vulnerability identification. Include specific tool commands and explain how you prioritize findings for exploitation.',
    keywords: ['nmap', 'port scanning', 'service enumeration', 'OS fingerprinting', 'vulnerability', 'reconnaissance', 'banner grabbing', 'network mapping'],
    tools: ['nmap', 'Masscan', 'Nessus'],
    framework: 'PTES',
  },

  {
    id: 'lab-packet-capture-analysis',
    title: 'Packet Capture Deep Dive',
    description: 'Analyze a network packet capture to reconstruct a security incident.',
    category: 'Network Security',
    difficulty: 'intermediate',
    estimatedMin: 45,
    xpReward: 170,
    accentColor: '#60a5fa',
    scenario: 'You have a PCAP file from an incident where an internal host at 192.168.1.50 was suspected of being compromised. The capture is 200MB from a 2-hour window. You need to identify what happened.',
    tasks: ['Describe your systematic approach to analyzing a large PCAP file', 'List the Wireshark display filters you would use to identify suspicious connections', 'Explain how to follow a TCP stream and what you look for in cleartext vs encrypted sessions', 'Describe how to extract file transfers, DNS queries, and credentials from a PCAP'],
    labPrompt: 'Analyze a PCAP from a suspected compromised host. Walk through your complete analysis methodology: how you approach a large capture file, which Wireshark filters you apply, how you identify C2 communication patterns, how you extract transferred files, and how you build a timeline of the attacker\'s actions.',
    keywords: ['Wireshark', 'PCAP', 'TCP stream', 'C2 communication', 'DNS analysis', 'HTTP traffic', 'file extraction', 'timeline'],
    tools: ['Wireshark', 'tcpdump', 'NetworkMiner'],
    framework: 'NIST SP 800-61',
  },

  {
    id: 'lab-firewall-pentest',
    title: 'Firewall Rule Bypass Techniques',
    description: 'Understand how attackers bypass firewall rules and how to prevent bypass techniques.',
    category: 'Network Security',
    difficulty: 'advanced',
    estimatedMin: 50,
    xpReward: 200,
    accentColor: '#60a5fa',
    scenario: 'During an authorized penetration test, the target organization has a firewall blocking all outbound traffic except port 80 (HTTP) and 443 (HTTPS). You need to demonstrate to the security team how an attacker would establish persistence despite these restrictions.',
    tasks: ['Describe at least 3 techniques to establish C2 over allowed ports', 'Explain how HTTP/HTTPS tunneling works and how to detect it', 'Describe how DNS tunneling evades this firewall configuration', 'Write the firewall rules and monitoring controls that would detect these bypass techniques'],
    labPrompt: 'During an authorized pentest, you face egress filtering allowing only HTTP and HTTPS. Describe the bypass techniques available to an attacker: HTTP/HTTPS tunneling, DNS tunneling, and domain fronting. For each technique: explain the mechanism, the tools used, and the specific network monitoring control that detects it.',
    keywords: ['C2 tunneling', 'HTTP tunneling', 'DNS tunneling', 'domain fronting', 'egress filtering', 'firewall bypass', 'covert channel', 'deep packet inspection'],
    tools: ['Chisel', 'iodine', 'ncat'],
    framework: 'MITRE ATT&CK T1572',
  },

  {
    id: 'lab-wireless-attack',
    title: 'Wi-Fi Security Assessment',
    description: 'Conduct an authorized wireless security assessment to identify weaknesses in Wi-Fi infrastructure.',
    category: 'Network Security',
    difficulty: 'advanced',
    estimatedMin: 45,
    xpReward: 180,
    accentColor: '#60a5fa',
    scenario: 'An organization asks you to conduct an authorized wireless security assessment. They have 3 SSIDs: "CorpNet" (WPA2-PSK), "CorpGuest" (open), and "CorpSecure" (WPA2-Enterprise/802.1X). All APs are Cisco Meraki.',
    tasks: ['Describe the methodology for assessing each network type differently', 'Explain the specific attack techniques applicable to WPA2-PSK and how the passphrase strength matters', 'Describe how 802.1X can still be attacked (EAP downgrade, rogue AP)', 'Write the recommendations report addressing each finding'],
    labPrompt: 'Assess three Wi-Fi networks with different security configurations: WPA2-PSK, open guest network, and WPA2-Enterprise. Describe your assessment methodology for each, the specific attacks applicable (PSK cracking, client isolation bypass, EAP attacks), and your complete recommendations report with prioritized remediation steps.',
    keywords: ['WPA2-PSK', '802.1X', 'EAP', 'rogue AP', 'captive portal', 'client isolation', 'PSK cracking', 'wireless assessment'],
    tools: ['aircrack-ng', 'Hashcat', 'hostapd-wpe'],
    framework: 'SANS SWAT Checklist',
  },

  // ── IDENTITY & ACCESS MANAGEMENT ─────────────────────────────────────────

  {
    id: 'lab-ad-hardening',
    title: 'Active Directory Security Hardening',
    description: 'Identify and remediate critical Active Directory misconfigurations exploited by attackers.',
    category: 'Identity & Access Management',
    difficulty: 'advanced',
    estimatedMin: 60,
    xpReward: 220,
    accentColor: '#a78bfa',
    scenario: 'A penetration tester has delivered a report showing they compromised your entire Active Directory domain starting from a low-privilege user account. They used Kerberoasting to get service account credentials, exploited an unconstrained delegation server, and used BloodHound to find a path to Domain Admin.',
    tasks: ['Explain what Kerberoasting is and which accounts are vulnerable', 'Describe how unconstrained delegation can be exploited and how to remediate it', 'Explain the BloodHound attack path concept and how to identify high-risk paths in your own AD', 'Write a 90-day AD hardening roadmap addressing all three findings'],
    labPrompt: 'Your Active Directory was fully compromised using Kerberoasting, unconstrained delegation, and BloodHound attack paths. For each technique: explain the vulnerability, the specific attacker steps, the defensive configuration change (e.g., managed service accounts, constrained delegation), and how you detect exploitation in your logs.',
    keywords: ['Kerberoasting', 'unconstrained delegation', 'BloodHound', 'service accounts', 'Managed Service Account', 'constrained delegation', 'AD hardening', 'Domain Admin'],
    tools: ['BloodHound', 'Rubeus', 'PowerView'],
    framework: 'Microsoft Security Baseline',
  },

  {
    id: 'lab-mfa-bypass',
    title: 'MFA Bypass Attack Scenarios',
    description: 'Understand real-world MFA bypass techniques and implement phishing-resistant authentication.',
    category: 'Identity & Access Management',
    difficulty: 'intermediate',
    estimatedMin: 35,
    xpReward: 160,
    accentColor: '#a78bfa',
    scenario: 'Your organization uses SMS-based MFA for all employees. A threat intelligence report indicates that attackers are using MFA fatigue attacks (push bombing) and SIM swapping to bypass MFA at companies in your industry.',
    tasks: ['Explain how MFA fatigue / push bombing works and why users comply', 'Describe the SIM swapping attack and why SMS 2FA is vulnerable', 'Compare TOTP vs push notification vs FIDO2 security against these attacks', 'Write the policy and technical controls to migrate from SMS MFA to phishing-resistant FIDO2'],
    labPrompt: 'Your SMS-based MFA is vulnerable to SIM swapping and MFA fatigue attacks. Explain how each attack works, why users fall for push bombing, compare the security of TOTP vs push vs FIDO2 hardware keys, and write a migration plan to deploy FIDO2/WebAuthn company-wide including handling exceptions for users who cannot use hardware keys.',
    keywords: ['MFA fatigue', 'SIM swapping', 'FIDO2', 'WebAuthn', 'TOTP', 'push bombing', 'phishing-resistant MFA', 'passkeys'],
    tools: ['YubiKey', 'Okta', 'Duo Security'],
    framework: 'NIST SP 800-63B',
  },

  {
    id: 'lab-privileged-access',
    title: 'Privileged Access Management (PAM)',
    description: 'Design and implement a PAM solution to control and audit privileged account usage.',
    category: 'Identity & Access Management',
    difficulty: 'intermediate',
    estimatedMin: 40,
    xpReward: 170,
    accentColor: '#a78bfa',
    scenario: 'An audit reveals: 12 IT admins all share a single "sysadmin" account, root password on Linux servers was last changed 3 years ago and is shared via email, and 3 former employees still have active VPN accounts.',
    tasks: ['Define the risks created by each finding with specific attack scenarios', 'Design a PAM architecture using CyberArk or HashiCorp Vault principles', 'Describe how just-in-time (JIT) privileged access reduces the standing privilege attack surface', 'Write the privileged account policy covering naming, rotation, and offboarding'],
    labPrompt: 'Audit findings reveal shared admin accounts, stale root passwords, and active accounts for departed employees. For each finding: identify the specific attack risk (e.g., insider threat, credential sharing), describe the PAM control that addresses it (individual accounts, secret rotation, automated offboarding), and design a JIT privileged access workflow.',
    keywords: ['PAM', 'privileged access', 'just-in-time', 'CyberArk', 'secret rotation', 'shared accounts', 'offboarding', 'standing privilege'],
    tools: ['CyberArk', 'HashiCorp Vault', 'BeyondTrust'],
    framework: 'CIS Control 5',
  },

  {
    id: 'lab-zero-trust-identity',
    title: 'Zero Trust Identity Design',
    description: 'Design a Zero Trust identity architecture with continuous authentication and risk-based access.',
    category: 'Identity & Access Management',
    difficulty: 'advanced',
    estimatedMin: 50,
    xpReward: 190,
    accentColor: '#a78bfa',
    scenario: 'Your company is moving to a fully remote workforce. The previous perimeter-based model (VPN + corporate network) is being replaced. You must design an identity-centric Zero Trust architecture for 500 employees accessing both cloud SaaS and on-premise applications.',
    tasks: ['Define the core components of a Zero Trust identity architecture (IdP, MFA, device trust, SSO)', 'Describe how conditional access policies enforce context-aware authentication', 'Explain how you handle privileged access for IT admins under Zero Trust', 'Write a 6-month implementation roadmap'],
    labPrompt: 'Design a Zero Trust identity architecture for 500 remote employees. Define: your Identity Provider choice and configuration, FIDO2 MFA requirements, device trust assessment criteria (compliant device required), conditional access policies (block access from unmanaged devices, flag anomalous locations), and how you handle legacy apps that cannot support modern auth.',
    keywords: ['Zero Trust', 'conditional access', 'device trust', 'SSO', 'SAML', 'OIDC', 'Identity Provider', 'continuous authentication'],
    tools: ['Okta', 'Azure AD', 'CrowdStrike Zero Trust'],
    framework: 'NIST SP 800-207',
  },

  // ── INCIDENT RESPONSE ────────────────────────────────────────────────────

  {
    id: 'lab-ir-playbook',
    title: 'Build an Incident Response Playbook',
    description: 'Create a comprehensive IR playbook covering detection through post-incident review.',
    category: 'Incident Response',
    difficulty: 'intermediate',
    estimatedMin: 45,
    xpReward: 170,
    accentColor: '#fb923c',
    scenario: 'Your organization has no formal incident response plan. The CISO wants a playbook covering the 5 most common incident types before the next quarterly board meeting.',
    tasks: ['Define the 5 incident types and their severity tiers (P1-P4)', 'Write the detection-to-escalation workflow for each severity level', 'Define roles and responsibilities (Incident Commander, Technical Lead, Communications Lead)', 'Create a communication template for notifying executives and regulators'],
    labPrompt: 'Build an incident response playbook covering: credential compromise, malware infection, data breach, DDoS attack, and ransomware. For each: define detection criteria, initial triage steps, escalation threshold, containment actions, and communication templates. Define your P1-P4 severity matrix and the SLA for each level.',
    keywords: ['incident response', 'playbook', 'severity tier', 'escalation', 'incident commander', 'SLA', 'communication template', 'PICE cycle'],
    framework: 'NIST SP 800-61',
  },

  {
    id: 'lab-data-breach-response',
    title: 'Data Breach Response & Notification',
    description: 'Navigate the legal, technical, and communication requirements of a data breach.',
    category: 'Incident Response',
    difficulty: 'intermediate',
    estimatedMin: 40,
    xpReward: 165,
    accentColor: '#fb923c',
    scenario: 'An attacker has accessed an unprotected database containing 50,000 customer records including names, emails, phone numbers, and hashed passwords. The database was accessible for 14 days before discovery. Customers are in the EU, California, and New York.',
    tasks: ['Determine which regulations apply and their notification timelines (GDPR, CCPA, NY SHIELD)', 'Describe what you must include in each notification to regulators and affected individuals', 'Write the breach notification email to affected customers', 'Describe the technical remediation required before resuming normal operations'],
    labPrompt: 'Respond to a data breach affecting 50,000 customers across GDPR, CCPA, and NY SHIELD jurisdictions. Document: your legal notification obligations and deadlines for each regulation, what you tell regulators vs. affected individuals, the breach notification email text, and your complete technical remediation plan.',
    keywords: ['GDPR', 'CCPA', 'data breach notification', '72 hours', 'regulatory reporting', 'affected individuals', 'breach response', 'remediation'],
    framework: 'GDPR Article 33/34',
  },

  {
    id: 'lab-tabletop-exercise',
    title: 'Run a Tabletop Exercise',
    description: 'Design and facilitate a cybersecurity tabletop exercise for executive and technical teams.',
    category: 'Incident Response',
    difficulty: 'intermediate',
    estimatedMin: 50,
    xpReward: 175,
    accentColor: '#fb923c',
    scenario: 'Your CISO wants to run a tabletop exercise simulating a ransomware attack before the annual audit. Participants will include the CEO, CFO, Legal, HR, IT Director, and the SOC team.',
    tasks: ['Design the ransomware scenario with 5 inject points that escalate severity', 'Write discussion questions for each inject targeting the specific role', 'Define the learning objectives and what decisions you want to test', 'Create the after-action report template to capture lessons learned'],
    labPrompt: 'Design a 2-hour ransomware tabletop exercise for a mixed executive and technical audience. Create 5 escalating scenario injects, write role-specific discussion questions (CEO focuses on crisis communication, CFO on payment decision, Legal on notification obligations, IT on technical response), define your learning objectives, and create the after-action report template.',
    keywords: ['tabletop exercise', 'scenario inject', 'ransomware response', 'crisis communication', 'lessons learned', 'executive decision', 'payment decision', 'after-action report'],
    framework: 'FEMA CPG 101',
  },

  {
    id: 'lab-memory-forensics',
    title: 'Memory Forensics with Volatility',
    description: 'Extract malware artifacts, process injections, and network connections from a memory dump.',
    category: 'Incident Response',
    difficulty: 'advanced',
    estimatedMin: 60,
    xpReward: 220,
    accentColor: '#fb923c',
    scenario: 'A Windows Server shows signs of compromise. You have captured a 4GB RAM dump. The incident response team needs to determine what malware is present, what credentials may have been stolen, and what network connections were established.',
    tasks: ['List the Volatility 3 commands to enumerate processes, network connections, and command history', 'Explain how to detect process injection using malfind and dlllist', 'Describe how to extract potential credentials from LSASS process memory', 'Explain how to identify persistence mechanisms from memory alone'],
    labPrompt: 'Analyze a Windows memory dump for a compromised server. Describe your complete Volatility 3 workflow: process enumeration, network connection extraction, LSASS analysis for credential theft, memory injection detection with malfind, and how you identify C2 communication from network artifacts in memory. Include specific commands.',
    keywords: ['Volatility', 'memory forensics', 'LSASS', 'process injection', 'malfind', 'network connections', 'credential extraction', 'memory dump'],
    tools: ['Volatility 3', 'MemProcFS', 'Redline'],
    framework: 'NIST SP 800-61',
  },

  // ── CLOUD SECURITY ───────────────────────────────────────────────────────

  {
    id: 'lab-aws-pentest',
    title: 'AWS Environment Penetration Testing',
    description: 'Conduct authorized AWS penetration testing covering IAM, EC2, S3, and Lambda services.',
    category: 'Cloud Security',
    difficulty: 'advanced',
    estimatedMin: 60,
    xpReward: 230,
    accentColor: '#38bdf8',
    scenario: 'You are conducting an authorized AWS penetration test. Your initial access is an IAM user with limited S3 read permissions. The goal is to demonstrate the impact of privilege escalation and lateral movement within the cloud environment.',
    tasks: ['Describe how you enumerate your current permissions using AWS CLI', 'Explain at least 2 privilege escalation paths from limited S3 permissions', 'Describe how to pivot from an EC2 instance to AWS credentials via IMDS', 'Write the test findings report with business impact and remediation'],
    labPrompt: 'Starting with limited AWS IAM credentials, describe your penetration testing methodology: how you enumerate current permissions with aws iam get-user and aws iam simulate-principal-policy, two privilege escalation paths (iam:CreatePolicyVersion or PassRole+Lambda), how to exploit IMDS to steal EC2 role credentials, and how to enumerate and download exposed S3 objects.',
    keywords: ['AWS pentest', 'IAM enumeration', 'privilege escalation', 'IMDS', 'PassRole', 'S3 bucket', 'CloudTrail evasion', 'ScoutSuite'],
    tools: ['Pacu', 'ScoutSuite', 'aws-cli'],
    framework: 'AWS Penetration Testing Policy',
  },

  {
    id: 'lab-terraform-security',
    title: 'Secure Terraform Infrastructure',
    description: 'Scan and remediate security issues in Terraform configurations before deployment.',
    category: 'Cloud Security',
    difficulty: 'intermediate',
    estimatedMin: 40,
    xpReward: 165,
    accentColor: '#38bdf8',
    scenario: 'A developer has submitted a Terraform pull request that creates an EC2 instance, an RDS database, an S3 bucket, and a security group. Checkov scan shows 12 findings. You must review and remediate before approval.',
    tasks: ['Identify the 5 most critical Terraform security misconfigurations (security group, S3, RDS, EC2)', 'Write the corrected Terraform HCL for each finding', 'Describe how to integrate Checkov or tfsec into the CI/CD pipeline as a blocking gate', 'Write the IaC security policy for your team'],
    labPrompt: 'Review a Terraform PR with these findings: security group with ingress from 0.0.0.0/0 on port 22, S3 bucket with public ACL, RDS with no encryption and public accessibility, EC2 without IMDSv2 enforcement, and no CloudTrail logging resource. For each: explain the risk, write the corrected HCL, and describe the Checkov rule ID that catches it.',
    keywords: ['Terraform', 'Checkov', 'IaC security', 'security group', 'IMDSv2', 'S3 ACL', 'RDS encryption', 'CI/CD gate'],
    tools: ['Checkov', 'tfsec', 'Terraform'],
    framework: 'CIS AWS Foundations',
  },

  {
    id: 'lab-cloud-detection',
    title: 'Build Cloud Threat Detection Rules',
    description: 'Create CloudWatch alarms and GuardDuty custom threat intelligence lists for cloud attack scenarios.',
    category: 'Cloud Security',
    difficulty: 'intermediate',
    estimatedMin: 45,
    xpReward: 175,
    accentColor: '#38bdf8',
    scenario: 'Your AWS environment has GuardDuty and CloudTrail enabled. The security team wants automated alerts for: unauthorized AWS CLI usage from a new country, root account login, EC2 instance launched in an unexpected region, and mass S3 object deletion.',
    tasks: ['Write the CloudWatch Events (EventBridge) rule for each scenario', 'Describe the GuardDuty finding types that would fire for each scenario', 'Design the automated Lambda response for each alert type', 'Write the runbook an analyst follows when each alert fires'],
    labPrompt: 'Build cloud detection rules for four attack scenarios in AWS. For each scenario: write the specific EventBridge rule (event pattern JSON), identify the GuardDuty finding type that would also catch it, design the Lambda automation response (e.g., deny-all policy attachment, instance isolation), and write the analyst runbook for manual investigation steps.',
    keywords: ['EventBridge', 'GuardDuty', 'CloudTrail', 'root account', 'Lambda automation', 'cloud detection', 'SOAR', 'runbook'],
    tools: ['AWS GuardDuty', 'CloudWatch', 'Lambda'],
    framework: 'AWS Security Hub',
  },

  // ── DEVSECOPS ───────────────────────────────────────────────────────────

  {
    id: 'lab-sast-integration',
    title: 'Integrate SAST into CI/CD Pipeline',
    description: 'Add static application security testing to a GitHub Actions workflow with quality gates.',
    category: 'DevSecOps',
    difficulty: 'intermediate',
    estimatedMin: 40,
    xpReward: 165,
    accentColor: '#fb923c',
    scenario: 'A web application team pushes code to GitHub. Currently there is no security scanning in the pipeline. The security team wants: dependency vulnerability scanning, SAST for code-level vulnerabilities, and secrets detection — all without slowing down developer velocity.',
    tasks: ['Design the GitHub Actions workflow with security scanning stages', 'Choose the right tool for each scan type (Snyk/Dependabot, Semgrep/CodeQL, GitLeaks/Trufflehog)', 'Define thresholds for blocking vs. warning (Critical CVEs block; Medium warn)', 'Write the developer-facing vulnerability report format'],
    labPrompt: 'Design a security scanning GitHub Actions workflow for a Node.js web application. Specify: the exact tools for dependency scanning, SAST, and secrets detection; the workflow YAML structure with parallel jobs; the severity thresholds that block a merge vs. create a warning; and how you handle false positives so developers aren\'t blocked by noise.',
    keywords: ['SAST', 'GitHub Actions', 'Semgrep', 'Snyk', 'secrets scanning', 'Trufflehog', 'dependency scanning', 'quality gate'],
    tools: ['Semgrep', 'Snyk', 'GitLeaks', 'Trivy'],
    framework: 'OWASP SAMM',
  },

  {
    id: 'lab-secrets-management',
    title: 'Secrets Management in DevOps',
    description: 'Identify and eliminate hardcoded secrets; implement a secrets management solution.',
    category: 'DevSecOps',
    difficulty: 'intermediate',
    estimatedMin: 35,
    xpReward: 155,
    accentColor: '#fb923c',
    scenario: 'During a code audit, you discover: AWS access keys in a .env file committed to GitHub, a database password hardcoded in application.properties, API keys in Slack messages, and database credentials in Docker environment variables visible in image history.',
    tasks: ['Assess the risk of each secret exposure scenario', 'Describe the immediate remediation steps (rotate secrets before anything else)', 'Design a secrets management architecture using HashiCorp Vault or AWS Secrets Manager', 'Write developer guidelines for secrets handling that prevent future incidents'],
    labPrompt: 'Respond to a secrets sprawl audit showing credentials in GitHub, config files, Slack, and Docker images. For each vector: assess the risk and who may have accessed the secret, describe immediate remediation (rotation, revocation), design a secrets management workflow using Vault or AWS Secrets Manager, and write developer guidelines and pre-commit hooks to prevent future exposures.',
    keywords: ['secrets management', 'HashiCorp Vault', 'AWS Secrets Manager', 'credential rotation', 'pre-commit hook', 'GitLeaks', 'Docker secrets', 'environment variables'],
    tools: ['HashiCorp Vault', 'git-secrets', 'trufflehog'],
    framework: 'CIS Control 18',
  },

  {
    id: 'lab-container-hardening',
    title: 'Harden a Docker Container',
    description: 'Apply Docker security best practices to reduce container attack surface.',
    category: 'DevSecOps',
    difficulty: 'intermediate',
    estimatedMin: 40,
    xpReward: 165,
    accentColor: '#fb923c',
    scenario: 'A developer has created a Dockerfile for a web application. The image uses FROM ubuntu:latest, runs as root, has no health check, copies the .env file into the image, and exposes port 22 for SSH debugging.',
    tasks: ['Identify every security issue in the Dockerfile description', 'Write the secure Dockerfile with a minimal base image, non-root user, and no secrets', 'Describe the docker run flags that reduce container privilege', 'Define the Trivy scan integration to detect image CVEs'],
    labPrompt: 'Audit and rewrite an insecure Dockerfile. Identify issues: root execution, full Ubuntu base, .env file in image, SSH port, no image signing. Write the secure version: use python:3.12-slim or distroless, create a non-root user (USER appuser), use multi-stage build to exclude dev dependencies, use Docker secrets instead of env vars for credentials, and add Trivy scanning to CI.',
    keywords: ['Docker hardening', 'non-root user', 'distroless', 'multi-stage build', 'Trivy', 'Docker secrets', 'image signing', 'container security'],
    tools: ['Docker', 'Trivy', 'Hadolint'],
    framework: 'CIS Docker Benchmark',
  },

  // ── CRYPTOGRAPHY & DATA PROTECTION ───────────────────────────────────────

  {
    id: 'lab-crypto-implementation',
    title: 'Cryptography Implementation Audit',
    description: 'Audit application cryptography for weak algorithms, poor key management, and implementation flaws.',
    category: 'Cryptography',
    difficulty: 'advanced',
    estimatedMin: 45,
    xpReward: 185,
    accentColor: '#00ff41',
    scenario: 'A code review reveals: passwords hashed with MD5 (no salt), symmetric encryption using ECB mode, TLS 1.0 enabled on the web server, RSA-512 used for API signing, and encryption keys stored alongside encrypted data in the same database.',
    tasks: ['Explain the specific weakness of each cryptographic implementation', 'Describe the attack that exploits each weakness', 'Write the corrected implementation (algorithm, mode, key size, key management)', 'Create a cryptographic standards policy for your development team'],
    labPrompt: 'Audit five cryptographic implementation flaws: MD5 password hashing, AES-ECB encryption, TLS 1.0 enablement, RSA-512 key, and co-located keys and ciphertext. For each flaw: explain why it is weak (e.g., ECB mode reveals patterns, MD5 has collision attacks), the corrected implementation (bcrypt, AES-256-GCM, TLS 1.3, RSA-4096, KMS), and write a cryptographic standards policy.',
    keywords: ['MD5', 'bcrypt', 'AES-ECB', 'AES-GCM', 'TLS 1.3', 'RSA key size', 'key management', 'cryptographic standards'],
    framework: 'NIST SP 800-175B',
  },

  {
    id: 'lab-pki-management',
    title: 'PKI & Certificate Management',
    description: 'Design and manage a PKI infrastructure; respond to a certificate-related incident.',
    category: 'Cryptography',
    difficulty: 'advanced',
    estimatedMin: 50,
    xpReward: 195,
    accentColor: '#00ff41',
    scenario: 'Your organization\'s wildcard TLS certificate (*.company.com) expires in 3 days and was not on any monitoring list. Additionally, the private key was stored unencrypted on a shared file server accessible to 200 employees.',
    tasks: ['Describe the immediate steps to renew and deploy the certificate without downtime', 'Explain the risk of an unencrypted private key on a shared server', 'Design a certificate lifecycle management process using automation', 'Describe how certificate transparency logs can help detect unauthorized certificates'],
    labPrompt: 'Respond to a certificate emergency: wildcard cert expiring in 3 days, private key exposed to 200 users on a shared drive. Immediate steps: revoke the compromised private key, issue new cert via Let\'s Encrypt or internal CA, deploy to all 20 services. Design ongoing process: automated cert monitoring (cert-manager, CertWatch), private key HSM storage, rotation automation, and CT log monitoring.',
    keywords: ['PKI', 'TLS certificate', 'private key', 'certificate rotation', 'Let\'s Encrypt', 'ACME', 'HSM', 'certificate transparency'],
    tools: ['cert-manager', 'OpenSSL', 'Let\'s Encrypt'],
    framework: 'NIST SP 800-57',
  },

  {
    id: 'lab-ransomware-recovery',
    title: 'Ransomware Recovery Planning',
    description: 'Design backup and recovery architecture that survives ransomware attack on primary systems.',
    category: 'Incident Response',
    difficulty: 'intermediate',
    estimatedMin: 45,
    xpReward: 175,
    accentColor: '#fb923c',
    scenario: 'A client asks you to review their backup strategy. Currently: daily backups to a network share on the same domain, 30-day retention, no testing of restores, and backups run with domain admin credentials. A recent ransomware attack at a peer company encrypted all backups too.',
    tasks: ['Identify every backup security failure in the current setup', 'Design a ransomware-resistant backup architecture using the 3-2-1-1-0 rule', 'Describe immutable backup solutions and how they prevent encryption', 'Write the backup testing procedure and RTO/RPO requirements'],
    labPrompt: 'Redesign a ransomware-vulnerable backup strategy. Current failures: domain-joined backup server (encrypted with domain), domain admin credentials (stolen by ransomware), no immutability, no restore testing. Design: 3-2-1-1-0 backup strategy, offline/air-gapped copy, immutable object storage (S3 Object Lock or Veeam hardened repo), separate credentials, automated restore testing, and your RTO/RPO definitions.',
    keywords: ['3-2-1-1-0', 'immutable backup', 'air gap', 'S3 Object Lock', 'RTO', 'RPO', 'backup testing', 'ransomware recovery'],
    tools: ['Veeam', 'AWS S3 Object Lock', 'Cohesity'],
    framework: 'NIST SP 800-34',
  },

  // ── COMPLIANCE & GOVERNANCE ───────────────────────────────────────────────

  {
    id: 'lab-pci-assessment',
    title: 'PCI DSS Compliance Assessment',
    description: 'Evaluate an e-commerce environment against PCI DSS v4.0 requirements.',
    category: 'Compliance & Governance',
    difficulty: 'intermediate',
    estimatedMin: 45,
    xpReward: 175,
    accentColor: '#facc15',
    scenario: 'An e-commerce company processes 2 million card transactions per year (SAQ D merchant). They store full PAN numbers in a MySQL database, use no tokenization, have no network segmentation between the web server and database, and share admin credentials.',
    tasks: ['Identify the PCI DSS requirements that are violated by each finding', 'Determine the merchant level and assessment requirements (SAQ vs QSA)', 'Describe the technical remediation for each PCI violation', 'Create a 12-month PCI compliance roadmap'],
    labPrompt: 'Assess an e-commerce environment against PCI DSS v4.0. For each finding (stored PANs, no tokenization, no segmentation, shared credentials): cite the specific PCI DSS requirement violated, the risk, and the remediation. Determine their merchant level and whether they need a QSA or SAQ. Design a 12-month roadmap to achieve compliance.',
    keywords: ['PCI DSS', 'PAN storage', 'tokenization', 'network segmentation', 'QSA', 'SAQ', 'cardholder data', 'merchant level'],
    framework: 'PCI DSS v4.0',
  },

  {
    id: 'lab-gdpr-dpia',
    title: 'GDPR Data Protection Impact Assessment',
    description: 'Conduct a DPIA for a new product feature involving personal data processing.',
    category: 'Compliance & Governance',
    difficulty: 'intermediate',
    estimatedMin: 40,
    xpReward: 165,
    accentColor: '#facc15',
    scenario: 'Your company plans to launch a new AI feature that analyzes employee emails and calendar data to suggest productivity improvements. The feature processes data from all EU employees. Legal and HR have concerns.',
    tasks: ['Determine whether a DPIA is legally required under GDPR Article 35', 'Identify all personal data being processed and categorize by sensitivity', 'Describe the risks to data subjects and proposed mitigations', 'Write the DPIA summary document for DPO review'],
    labPrompt: 'Conduct a GDPR Data Protection Impact Assessment for an AI feature processing EU employee email and calendar data. Determine if Article 35 DPIA is required (yes — systematic monitoring of employees). Identify: personal data categories, legal basis for processing, data subject risks (profiling, discrimination), and mitigations (data minimization, employee consent, retention limits). Write the DPO review document.',
    keywords: ['GDPR', 'DPIA', 'Article 35', 'data minimization', 'legal basis', 'data subject rights', 'DPO', 'legitimate interest'],
    framework: 'GDPR Article 35',
  },

  {
    id: 'lab-hipaa-assessment',
    title: 'HIPAA Security Rule Assessment',
    description: 'Evaluate healthcare systems against HIPAA Security Rule administrative, physical, and technical safeguards.',
    category: 'Compliance & Governance',
    difficulty: 'intermediate',
    estimatedMin: 40,
    xpReward: 165,
    accentColor: '#facc15',
    scenario: 'A healthcare clinic uses: unencrypted laptops storing patient records, shared login credentials for the EHR system, PHI emailed via unencrypted Gmail, no workforce security training, and no Business Associate Agreements (BAAs) with cloud vendors.',
    tasks: ['Map each finding to the specific HIPAA Security Rule safeguard (administrative/physical/technical)', 'Prioritize remediation by risk to patients', 'Describe the breach notification requirements if PHI was exposed', 'Create a HIPAA risk assessment template'],
    labPrompt: 'Assess a healthcare clinic against HIPAA Security Rule. Map findings to safeguards: unencrypted laptops (Technical: Encryption), shared EHR credentials (Technical: Unique User ID), unencrypted Gmail PHI (Technical: Transmission Encryption), no training (Administrative: Security Awareness), missing BAAs (Administrative: BA Agreements). Prioritize by patient risk and write breach notification obligations.',
    keywords: ['HIPAA', 'PHI', 'Security Rule', 'BAA', 'encryption', 'unique user ID', 'breach notification', 'administrative safeguards'],
    framework: 'HIPAA Security Rule 45 CFR Part 164',
  },

  {
    id: 'lab-soc2-audit',
    title: 'SOC 2 Type II Audit Preparation',
    description: 'Prepare for a SOC 2 Type II audit by mapping controls to Trust Service Criteria.',
    category: 'Compliance & Governance',
    difficulty: 'advanced',
    estimatedMin: 50,
    xpReward: 195,
    accentColor: '#facc15',
    scenario: 'A SaaS company needs to pass a SOC 2 Type II audit to close enterprise deals. The audit covers the Security and Availability criteria over a 12-month period. You have 3 months to prepare.',
    tasks: ['List the key controls required for Security (CC) and Availability (A1) Trust Service Criteria', 'Identify the most common SOC 2 audit failures and how to prevent them', 'Describe how to gather and organize evidence for a 12-month period', 'Write the vendor risk assessment process required for SOC 2'],
    labPrompt: 'Prepare a SaaS company for SOC 2 Type II covering Security and Availability criteria. Map controls to criteria: CC6.1 (logical access), CC7.2 (monitoring), A1.2 (availability commitments). Describe evidence collection for 12 months, common failures (access reviews not completed, vulnerability management gaps), vendor risk management process, and your 3-month pre-audit preparation timeline.',
    keywords: ['SOC 2', 'Trust Service Criteria', 'logical access', 'monitoring', 'vendor risk', 'evidence collection', 'access review', 'audit preparation'],
    framework: 'AICPA SOC 2',
  },

  // ── WEB APPLICATION SECURITY ─────────────────────────────────────────────

  {
    id: 'lab-burp-suite-basics',
    title: 'Burp Suite Web Testing Workflow',
    description: 'Use Burp Suite Pro to intercept, modify, and test web application requests for vulnerabilities.',
    category: 'Web Application Security',
    difficulty: 'intermediate',
    estimatedMin: 45,
    xpReward: 175,
    accentColor: '#f87171',
    scenario: 'You have authorized access to test a web application\'s API. The app has an e-commerce backend with user accounts, product listings, and an order system. You must find vulnerabilities using Burp Suite within a 4-hour engagement window.',
    tasks: ['Describe your Burp Suite setup and scope configuration', 'Explain how to use Burp Scanner vs manual testing with Repeater', 'Describe how to test for IDOR by manipulating order IDs and user IDs', 'Show how to use Burp Intruder for authentication brute force (within authorized scope)'],
    labPrompt: 'Conduct an authorized web app test using Burp Suite. Describe: proxy setup, scope definition, and passive vs active scanning. Use Repeater to test for IDOR on /api/orders/{id} by changing order IDs. Use Intruder for username enumeration on the login endpoint. Test the password reset function for token predictability. Document each finding with the exact HTTP request/response.',
    keywords: ['Burp Suite', 'IDOR', 'Repeater', 'Intruder', 'passive scan', 'active scan', 'password reset', 'token enumeration'],
    tools: ['Burp Suite Pro', 'OWASP ZAP'],
    framework: 'OWASP Testing Guide',
  },

  {
    id: 'lab-api-security-testing',
    title: 'REST API Security Testing',
    description: 'Test REST APIs for authentication, authorization, and injection vulnerabilities.',
    category: 'Web Application Security',
    difficulty: 'intermediate',
    estimatedMin: 45,
    xpReward: 175,
    accentColor: '#f87171',
    scenario: 'You are testing a REST API documented in Swagger/OpenAPI spec. The API has endpoints for user management, product catalog, and payment processing. All endpoints require Bearer token authentication.',
    tasks: ['Describe how to test JWT token security (alg:none, weak secret, missing expiry)', 'Explain testing methodology for BOLA (Broken Object Level Authorization)', 'Describe how to test for mass assignment vulnerabilities in POST/PATCH requests', 'Show how to test rate limiting on sensitive endpoints'],
    labPrompt: 'Test a REST API with JWT authentication for OWASP API Top 10. Describe: testing JWT security (decode with jwt.io, try alg:none, test expired tokens), BOLA testing on /api/users/{id} and /api/orders/{id}, mass assignment test by sending admin:true in JSON body, and rate limiting test using Burp Intruder to send 100 requests/second to /api/auth/login.',
    keywords: ['JWT', 'BOLA', 'mass assignment', 'rate limiting', 'OWASP API Top 10', 'Swagger', 'Bearer token', 'API testing'],
    tools: ['Burp Suite', 'Postman', 'jwt.io'],
    framework: 'OWASP API Security Top 10',
  },

  {
    id: 'lab-xss-advanced',
    title: 'Advanced XSS Exploitation',
    description: 'Exploit DOM-based XSS, CSP bypass, and stored XSS in realistic web application scenarios.',
    category: 'Web Application Security',
    difficulty: 'advanced',
    estimatedMin: 50,
    xpReward: 190,
    accentColor: '#f87171',
    scenario: 'A web application uses a CSP header: "script-src \'self\' https://cdn.jquery.com". The app has a stored XSS vulnerability in a comment field but the CSP blocks your basic <script> payload. You need to demonstrate impact to the development team.',
    tasks: ['Explain why the basic <script> payload fails with this CSP', 'Describe the JSONP CSP bypass technique using the jquery CDN', 'Show how to use a nonce-based bypass if the CSP uses nonces', 'Describe the business impact of stored XSS with session theft payload'],
    labPrompt: 'Exploit stored XSS despite a Content Security Policy that allows scripts from self and jquery CDN. Explain: why inline scripts are blocked, how JSONP endpoints on allowed domains enable CSP bypass, write the CSP bypass payload using jquery CDN JSONP, demonstrate session cookie theft impact, and write the corrected CSP that prevents bypass (no JSONP, strict-dynamic, nonce).',
    keywords: ['XSS', 'CSP bypass', 'JSONP', 'nonce', 'stored XSS', 'session theft', 'Content Security Policy', 'script-src'],
    tools: ['Burp Suite', 'Browser DevTools'],
    framework: 'OWASP Testing Guide v4.2',
  },

  // ── OSINT & THREAT INTELLIGENCE ──────────────────────────────────────────

  {
    id: 'lab-osint-investigation',
    title: 'OSINT Investigation Techniques',
    description: 'Use open-source intelligence techniques to profile a threat actor or investigate a breach.',
    category: 'Threat Intelligence',
    difficulty: 'intermediate',
    estimatedMin: 45,
    xpReward: 175,
    accentColor: '#e879f9',
    scenario: 'You receive a phishing email containing a link to a newly registered domain. Intelligence suggests the domain is part of a campaign targeting your industry. You need to investigate the campaign infrastructure using only open-source tools.',
    tasks: ['Describe the OSINT tools and techniques to pivot from a single domain', 'Explain how to find related infrastructure (same registrar, IP range, SSL cert)', 'Describe how Shodan and Censys help identify C2 infrastructure', 'Show how to map a threat actor\'s full campaign using passive DNS'],
    labPrompt: 'Investigate a phishing domain "secure-login-update.com" using OSINT only. Describe your pivot chain: WHOIS for registrar and registration date, passive DNS for historically resolved IPs, Shodan to find other domains on the same IP, SSL certificate transparency for related domains, VirusTotal for related malware samples, and URLScan.io for page content. Build a threat actor infrastructure map.',
    keywords: ['OSINT', 'passive DNS', 'Shodan', 'Censys', 'certificate transparency', 'WHOIS', 'infrastructure mapping', 'threat actor'],
    tools: ['Shodan', 'VirusTotal', 'URLScan.io', 'WHOIS'],
    framework: 'MITRE ATT&CK',
  },

  {
    id: 'lab-ioc-hunting',
    title: 'IOC Threat Hunting at Scale',
    description: 'Hunt for threat actor IOCs across enterprise logs using SIEM queries and EDR pivots.',
    category: 'Threat Intelligence',
    difficulty: 'advanced',
    estimatedMin: 50,
    xpReward: 195,
    accentColor: '#e879f9',
    scenario: 'CISA issues an advisory about a ransomware group using: 5 specific IP addresses for C2, 3 domain names, a unique mutex "Global\\MsMpEngCP", and a YARA rule matching a packed binary. You have 500 endpoints and 90 days of SIEM logs.',
    tasks: ['Write the SIEM queries to hunt for each IOC type across 90 days of logs', 'Describe how you use your EDR to hunt for the mutex across live endpoints', 'Explain how to prioritize triage when you find 20 IOC matches', 'Write the threat hunt report summarizing findings'],
    labPrompt: 'Hunt for ransomware group IOCs across your enterprise. Write Splunk SPL queries to: search proxy logs for the 5 C2 IPs and 3 domains (last 90 days), search DNS logs for domain queries, search network flow logs for C2 IP communication. Describe EDR queries for the mutex in process memory. Explain how you triage 20 matches (which systems to investigate first) and write the hunt report format.',
    keywords: ['IOC hunting', 'SIEM query', 'EDR hunting', 'mutex', 'YARA', 'C2 IP', 'SPL', 'threat hunting'],
    tools: ['Splunk', 'CrowdStrike Falcon', 'MISP'],
    framework: 'MITRE ATT&CK',
  },

  {
    id: 'lab-malware-report',
    title: 'Write a Malware Analysis Report',
    description: 'Document a malware sample analysis in a structured report for SOC and leadership audiences.',
    category: 'Threat Intelligence',
    difficulty: 'intermediate',
    estimatedMin: 40,
    xpReward: 165,
    accentColor: '#e879f9',
    scenario: 'You have completed analysis of a malware sample that turned out to be a Cobalt Strike beacon. You need to write a report for two audiences: the SOC team (technical) and the CISO (executive).',
    tasks: ['Define the structure of a technical malware analysis report', 'List all IOC types and formats to include (hash, IP, domain, YARA, network signatures)', 'Describe the MITRE ATT&CK mapping section', 'Write the executive summary paragraph for the CISO'],
    labPrompt: 'Write a dual-audience malware analysis report for a Cobalt Strike beacon sample. Technical section: file metadata (hash, size, compile time), behavioral analysis (process tree, network connections, persistence), IOCs (IP addresses, domains, certificate fingerprint, YARA rule), MITRE ATT&CK technique mapping (T1055 process injection, T1071 application layer protocol). Executive summary: business impact, infected systems, recommended actions.',
    keywords: ['malware report', 'Cobalt Strike', 'IOC', 'YARA rule', 'MITRE ATT&CK', 'executive summary', 'technical report', 'process injection'],
    framework: 'MITRE ATT&CK',
  },

  // ── ENDPOINT SECURITY ─────────────────────────────────────────────────────

  {
    id: 'lab-ransomware-forensics',
    title: 'Ransomware Forensic Investigation',
    description: 'Investigate a ransomware infection to determine patient zero, attack vector, and scope.',
    category: 'Endpoint Security',
    difficulty: 'advanced',
    estimatedMin: 60,
    xpReward: 220,
    accentColor: '#34d399',
    scenario: 'Monday morning, 200 Windows workstations have .lockbit extensions on all files. A ransom note is present. IT says the attack started sometime over the weekend. You must identify patient zero, initial access vector, and lateral movement path.',
    tasks: ['Describe how to identify patient zero from Windows Event Logs', 'Explain how Prefetch and LNK files help reconstruct the attack timeline', 'Describe how to trace lateral movement using Event ID 4648 and SMB logs', 'Identify what backup and recovery actions to take while forensics are ongoing'],
    labPrompt: 'Investigate a LockBit ransomware outbreak affecting 200 workstations. Describe: how you identify patient zero (earliest .lockbit extension timestamp correlation with logon events), what phishing/initial access vector evidence to look for (email gateway logs, browser download history), how Event IDs 4648 and 7045 reveal lateral movement and ransomware service installation, and your parallel recovery track.',
    keywords: ['ransomware forensics', 'patient zero', 'LockBit', 'Event ID 4648', 'lateral movement', 'Prefetch', 'LNK file', 'initial access'],
    tools: ['Volatility', 'Autopsy', 'Windows Event Viewer'],
    framework: 'NIST SP 800-61',
  },

  {
    id: 'lab-edr-alert-investigation',
    title: 'EDR Alert Deep Investigation',
    description: 'Investigate a complex EDR alert chain showing multi-stage attack behavior.',
    category: 'Endpoint Security',
    difficulty: 'advanced',
    estimatedMin: 50,
    xpReward: 200,
    accentColor: '#34d399',
    scenario: 'CrowdStrike Falcon fires: "Suspicious process tree: WINWORD.EXE → POWERSHELL.EXE (base64 args) → MSHTA.EXE → RUNDLL32.EXE (network connection to 185.x.x.x:443)". The endpoint belongs to a Finance department VP.',
    tasks: ['Interpret each step in the process tree as an ATT&CK technique', 'Describe how you decode and analyze each stage of the attack chain', 'Determine what the attackers likely have access to now', 'Write the complete incident response actions for this alert'],
    labPrompt: 'Investigate a CrowdStrike alert showing WINWORD→PowerShell→mshta→rundll32 process chain with C2 connection. Map each step: WINWORD macro execution (T1566.001), PowerShell with base64 (T1059.001), mshta LOLBin execution (T1218.005), rundll32 C2 staging (T1218.011). Describe how you decode base64, what you check in network traffic, what the VP\'s credentials and files may be at risk, and your response.',
    keywords: ['EDR', 'process tree', 'LOLBin', 'mshta', 'rundll32', 'macro execution', 'C2', 'MITRE ATT&CK'],
    tools: ['CrowdStrike Falcon', 'Wireshark', 'CyberChef'],
    framework: 'MITRE ATT&CK',
  },

  {
    id: 'lab-lateral-movement-detection',
    title: 'Detect Lateral Movement',
    description: 'Identify attacker lateral movement through Windows Event Log correlation and network analysis.',
    category: 'Endpoint Security',
    difficulty: 'advanced',
    estimatedMin: 50,
    xpReward: 200,
    accentColor: '#34d399',
    scenario: 'After an initial compromise of a helpdesk workstation, logs show connections to 15 different servers over 48 hours. You need to map the attacker\'s lateral movement path and determine which systems are compromised.',
    tasks: ['List the Windows Event IDs that indicate lateral movement (logon type 3, psexec, wmiexec)', 'Describe how to build a lateral movement graph using SIEM data', 'Explain how to differentiate attacker lateral movement from legitimate admin activity', 'Describe the containment strategy to stop movement without tipping off the attacker'],
    labPrompt: 'Map lateral movement from a compromised helpdesk workstation across 15 servers. Use Windows Event Logs: Event 4624 Type 3 (network logon), Event 7045 (service install for psexec), Event 4688 (process creation for wmiexec), and SMB Session logs. Build the movement graph, explain how to tell attacker traffic from legitimate IT admin activity, and design staged containment to isolate without alerting the attacker.',
    keywords: ['lateral movement', 'Event 4624', 'psexec', 'wmiexec', 'pass-the-hash', 'SMB', 'containment', 'network logon'],
    tools: ['Splunk', 'BloodHound', 'Wireshark'],
    framework: 'MITRE ATT&CK T1021',
  },

  // ── SOC & OPERATIONS ─────────────────────────────────────────────────────

  {
    id: 'lab-alert-triage',
    title: 'Mass Alert Triage Under Pressure',
    description: 'Triage 50 simultaneous SIEM alerts during a simulated attack and prioritize response.',
    category: 'Security Operations',
    difficulty: 'advanced',
    estimatedMin: 45,
    xpReward: 200,
    accentColor: '#facc15',
    scenario: 'It is 11 PM on a Friday. Your SIEM fires 50 alerts simultaneously. You are the only analyst on duty. Alerts include: brute force, port scans, privilege escalation attempts, a ransomware signature, and 20 "policy violation" alerts for USB usage.',
    tasks: ['Rank the 50 alerts by priority and justify your ranking', 'Describe your rapid triage methodology for each priority tier', 'Explain when you escalate vs. handle solo at 11 PM', 'Write the handoff brief for the morning shift'],
    labPrompt: 'Triage 50 simultaneous SIEM alerts as the sole overnight analyst. Rank by priority: ransomware signature is P1 (immediate), privilege escalation is P1, brute force with successful login is P1, brute force without success is P2, port scans are P3, USB policy violations are P4. Describe your rapid triage for each tier, when you wake up the IR manager, and write the detailed morning shift handoff report.',
    keywords: ['alert triage', 'priority ranking', 'ransomware', 'escalation', 'overnight analyst', 'P1 P2 P3', 'shift handoff', 'SOC analyst'],
    framework: 'NIST SP 800-61',
  },

  {
    id: 'lab-detection-engineering',
    title: 'Detection Engineering Workshop',
    description: 'Build, test, and tune detection rules for specific attacker techniques using Sigma format.',
    category: 'Security Operations',
    difficulty: 'advanced',
    estimatedMin: 55,
    xpReward: 210,
    accentColor: '#facc15',
    scenario: 'After a threat intel report about Scattered Spider (UNC3944) using social engineering for SIM swapping, then credential stuffing, then MFA fatigue attacks, your team wants detection rules for each phase.',
    tasks: ['Write Sigma rules for SIM swapping indicators (carrier SMS changes, impossible travel)', 'Write detection rules for credential stuffing (high failed logins + successful login pattern)', 'Describe MFA fatigue detection (many push notifications to same user in short window)', 'Define false positive scenarios and tuning approach for each rule'],
    labPrompt: 'Write Sigma detection rules for three Scattered Spider attack phases: 1) SIM swapping (impossible travel: successful login from new country within 2 hours of carrier contact), 2) credential stuffing (>20 failed logins from many IPs then success for same username), 3) MFA fatigue (>10 push notifications to one user in 5 minutes). Include false positive scenarios and tuning notes for each rule.',
    keywords: ['Sigma', 'detection engineering', 'credential stuffing', 'MFA fatigue', 'impossible travel', 'Scattered Spider', 'rule tuning', 'false positive'],
    tools: ['Sigma', 'Splunk', 'Microsoft Sentinel'],
    framework: 'MITRE ATT&CK',
  },

  {
    id: 'lab-soar-playbook',
    title: 'SOAR Automation Playbook Design',
    description: 'Design automated SOAR playbooks for common incident response scenarios.',
    category: 'Security Operations',
    difficulty: 'intermediate',
    estimatedMin: 40,
    xpReward: 170,
    accentColor: '#facc15',
    scenario: 'Your SOC receives 2,000 alerts per day. Analysis shows 40% are phishing reports from employees, 30% are brute force alerts, 15% are malware alerts, and 15% are misc. Your goal is to automate the first two categories to reduce analyst load.',
    tasks: ['Design a SOAR playbook for phishing triage (email analysis, URL detonation, auto-block)', 'Design a SOAR playbook for brute force (IP lookup, user notification, conditional lockout)', 'Describe the human review gate — when to auto-remediate vs. require analyst approval', 'Define the metrics you use to measure SOAR effectiveness'],
    labPrompt: 'Design SOAR automation for phishing and brute force alert categories. Phishing playbook: receive forwarded email, extract URLs/attachments, send to VirusTotal/URLScan.io, if malicious auto-block sender domain in email gateway and quarantine similar emails, notify reporter. Brute force playbook: extract source IP, check reputation, if malicious IP auto-block at firewall, if internal IP escalate to analyst. Define metrics: MTTR reduction, analyst hours saved.',
    keywords: ['SOAR', 'playbook automation', 'phishing triage', 'brute force', 'auto-remediation', 'human review gate', 'VirusTotal', 'MTTR'],
    tools: ['Splunk SOAR', 'Palo Alto XSOAR', 'Microsoft Sentinel'],
    framework: 'NIST SP 800-61',
  },

  // ── PHYSICAL & PERSONNEL SECURITY ─────────────────────────────────────────

  {
    id: 'lab-physical-pentest',
    title: 'Physical Security Assessment',
    description: 'Conduct an authorized physical penetration test to identify facility security weaknesses.',
    category: 'Physical Security',
    difficulty: 'intermediate',
    estimatedMin: 40,
    xpReward: 165,
    accentColor: '#94a3b8',
    scenario: 'An organization wants to test physical security at their headquarters. You have written authorization to attempt physical access to the server room, tailgate into the building, and plant USB devices in public areas as part of the assessment.',
    tasks: ['Describe a tailgating scenario and how you would execute it', 'Explain badge cloning techniques and the RFID vulnerabilities they exploit', 'Describe what you would do if you accessed the server room during the assessment', 'Write the physical security assessment report with prioritized findings'],
    labPrompt: 'Conduct an authorized physical penetration test at a corporate headquarters. Describe techniques attempted: tailgating (follow employee through badge-access door while carrying boxes), badge cloning (HID Prox cards are vulnerable; use a cloner from several feet away), USB drop (plant labeled USB in parking lot), server room access attempt. Document your findings, what you accessed, and prioritized physical security recommendations.',
    keywords: ['tailgating', 'badge cloning', 'RFID', 'USB drop', 'physical pentest', 'server room', 'access control', 'HID Prox'],
    framework: 'PTES',
  },

  {
    id: 'lab-insider-threat-program',
    title: 'Build an Insider Threat Program',
    description: 'Design a balanced insider threat program that detects threats while respecting employee privacy.',
    category: 'Physical Security',
    difficulty: 'intermediate',
    estimatedMin: 40,
    xpReward: 170,
    accentColor: '#94a3b8',
    scenario: 'Your organization has experienced two insider incidents this year: a disgruntled employee deleted critical databases before resigning, and a contractor exfiltrated source code to a competitor. Leadership wants an insider threat program.',
    tasks: ['Define the three categories of insider threat (malicious, negligent, compromised)', 'Describe the technical monitoring controls appropriate for each risk level', 'Explain how to balance monitoring with employee privacy and legal requirements', 'Design the insider threat investigation process and escalation path'],
    labPrompt: 'Design an insider threat program addressing malicious, negligent, and compromised insider categories. Define monitoring controls: DLP for data exfiltration detection, UEBA for behavioral anomalies, privileged user monitoring for IT admins. Explain legal boundaries: what you can monitor (work devices, corporate accounts) vs. what requires HR/Legal sign-off. Design the investigation trigger, evidence collection, and HR/Legal escalation process.',
    keywords: ['insider threat', 'DLP', 'UEBA', 'privileged user monitoring', 'behavioral analytics', 'employee monitoring', 'data exfiltration', 'privacy'],
    framework: 'NIST SP 800-53 AT-2',
  },

  // ── ADVANCED TOPICS ───────────────────────────────────────────────────────

  {
    id: 'lab-supply-chain-attack',
    title: 'Supply Chain Attack Analysis',
    description: 'Analyze the SolarWinds-style supply chain attack pattern and design defensive controls.',
    category: 'Advanced Threats',
    difficulty: 'advanced',
    estimatedMin: 50,
    xpReward: 210,
    accentColor: '#f87171',
    scenario: 'A security researcher reports that a popular open-source logging library used in your application has been backdoored in version 2.1.3. The library is installed on 50 of your servers and has been there for 3 months.',
    tasks: ['Describe how software supply chain attacks are executed', 'Explain how to determine if the backdoored version is in your environment', 'Describe your incident response for a potentially 3-month dwell time compromise', 'Design supply chain security controls to prevent similar attacks'],
    labPrompt: 'Respond to a backdoored open-source library with 3-month dwell time across 50 servers. Describe: how supply chain attacks embed malicious code in legitimate software updates, how you scan your environment for the specific vulnerable version using SBOM and dependency scanning, your incident response given 3 months of potential access, and supply chain prevention controls: SBOM generation, vendor security assessment, dependency pinning, private artifact repository scanning.',
    keywords: ['supply chain attack', 'SBOM', 'dependency scanning', 'SolarWinds', 'backdoor', 'dwell time', 'artifact repository', 'dependency pinning'],
    tools: ['Syft', 'Grype', 'Snyk'],
    framework: 'NIST SP 800-161',
  },

  {
    id: 'lab-apt-simulation',
    title: 'APT Attack Simulation & Defense',
    description: 'Simulate an Advanced Persistent Threat campaign and validate defensive controls at each stage.',
    category: 'Advanced Threats',
    difficulty: 'advanced',
    estimatedMin: 60,
    xpReward: 240,
    accentColor: '#f87171',
    scenario: 'You are running a red team exercise simulating APT29 (Cozy Bear) TTPs against your organization. The exercise tests your defenses across the full kill chain: initial access, persistence, credential access, lateral movement, and exfiltration.',
    tasks: ['Map the APT29 kill chain to specific MITRE ATT&CK techniques', 'Describe which blue team controls should detect each stage', 'Identify the likely detection failures (techniques that bypass current controls)', 'Write the red team report with MITRE heat map and prioritized recommendations'],
    labPrompt: 'Simulate APT29 TTPs across the attack lifecycle. Map to ATT&CK: T1566.001 spearphishing (initial access), T1053.005 scheduled tasks (persistence), T1003.001 LSASS dump (credential access), T1021.002 SMB lateral movement, T1048 exfiltration over alternative protocol. For each: describe the specific technique implementation, which control should catch it, and whether your current controls would detect it. Write heat map findings.',
    keywords: ['APT29', 'kill chain', 'MITRE ATT&CK', 'red team', 'scheduled task', 'LSASS', 'exfiltration', 'detection gap'],
    tools: ['Cobalt Strike', 'Atomic Red Team', 'MITRE ATT&CK Navigator'],
    framework: 'MITRE ATT&CK',
  },

  {
    id: 'lab-red-blue-purple',
    title: 'Purple Team Exercise Design',
    description: 'Design and run a purple team exercise that bridges red team attacks and blue team detection.',
    category: 'Advanced Threats',
    difficulty: 'advanced',
    estimatedMin: 55,
    xpReward: 215,
    accentColor: '#f87171',
    scenario: 'Your red team and blue team operate in silos. The CISO wants to run a purple team exercise to improve detection coverage specifically for the techniques most used by ransomware groups targeting your industry.',
    tasks: ['Define the purple team methodology and how it differs from traditional red/blue exercises', 'Select 10 high-priority ATT&CK techniques based on ransomware threat intel', 'Design the exercise format (announce vs. blind; collaborative vs. competitive)', 'Create the scoring rubric measuring detection coverage improvement'],
    labPrompt: 'Design a purple team exercise targeting ransomware group TTPs. Select 10 ATT&CK techniques (e.g., T1486 data encryption, T1490 inhibit system recovery, T1070 indicator removal). For each technique: red team executes the atomic test, blue team documents whether they detected it and from which data source, the gap is analyzed collaboratively. Define your pre/post detection coverage score, exercise format (collaborative/announced), and improvement metrics.',
    keywords: ['purple team', 'atomic red team', 'detection coverage', 'ATT&CK', 'ransomware TTPs', 'collaborative exercise', 'coverage scoring', 'detection gap'],
    tools: ['Atomic Red Team', 'MITRE ATT&CK Navigator', 'Caldera'],
    framework: 'MITRE ATT&CK',
  },

  {
    id: 'lab-vuln-disclosure',
    title: 'Responsible Vulnerability Disclosure',
    description: 'Navigate the responsible disclosure process when you find a critical vulnerability.',
    category: 'Advanced Threats',
    difficulty: 'intermediate',
    estimatedMin: 35,
    xpReward: 155,
    accentColor: '#f87171',
    scenario: 'While using a popular project management SaaS tool at work, you discover a SQL injection vulnerability that exposes all customer data. The vendor has no security contact listed, no bug bounty program, and does not respond to support tickets.',
    tasks: ['Describe the responsible disclosure process and standard timelines (90-day)', 'Explain how to find the vendor security contact using OSINT', 'Describe what evidence to preserve (without accessing other customers\' data)', 'Explain when and how to escalate to a coordinator (CERT/CC) or go public'],
    labPrompt: 'Navigate responsible disclosure of a critical SQLi vulnerability in a SaaS tool that holds your company\'s data. Describe: your initial disclosure approach (security@, HackerOne public programs), documentation of the vulnerability without exploiting it against real customer data, the 90-day disclosure timeline, how to use CERT/CC as a coordinator when vendor is unresponsive, and your legal considerations (CFAA, GDPR breach reporting if your data was exposed).',
    keywords: ['responsible disclosure', 'CVD', 'bug bounty', 'CERT/CC', '90 days', 'CFAA', 'coordinated disclosure', 'security contact'],
    framework: 'ISO/IEC 29147',
  },

  {
    id: 'lab-security-architecture-review',
    title: 'Security Architecture Review',
    description: 'Review and improve a proposed cloud-native application architecture for security weaknesses.',
    category: 'Advanced Threats',
    difficulty: 'advanced',
    estimatedMin: 55,
    xpReward: 215,
    accentColor: '#f87171',
    scenario: 'A development team presents their cloud-native architecture: React SPA calling REST APIs on ECS Fargate, PostgreSQL on RDS, user files on S3, authentication via JWT stored in localStorage, and no WAF or network segmentation.',
    tasks: ['Perform a threat model identifying the top 5 security risks in this architecture', 'Describe the security improvements required before going to production', 'Specify which AWS security services to add (WAF, VPC, Security Groups, KMS)', 'Define the security requirements that must be in the architectural decision records'],
    labPrompt: 'Review a cloud-native app architecture for security risks: JWT in localStorage (XSS theft), no WAF (OWASP attacks), RDS publicly accessible, S3 without encryption, flat network (ECS containers can reach all VPC resources). Threat model with STRIDE, define top 5 risks with CVSS estimates, recommend: HttpOnly cookie sessions, AWS WAF, RDS in private subnet, S3 SSE-KMS, VPC security groups for micro-segmentation.',
    keywords: ['security architecture', 'threat modeling', 'JWT localStorage', 'AWS WAF', 'RDS private subnet', 'micro-segmentation', 'STRIDE', 'security requirements'],
    framework: 'TOGAF Security Architecture',
  },
];

export function searchLabs(query: string, category?: string): StandaloneLab[] {
  const q = query.toLowerCase();
  return STANDALONE_LABS.filter(lab => {
    const matchesQuery = !query ||
      lab.title.toLowerCase().includes(q) ||
      lab.description.toLowerCase().includes(q) ||
      lab.keywords.some(k => k.toLowerCase().includes(q)) ||
      lab.category.toLowerCase().includes(q);
    const matchesCategory = !category || lab.category === category;
    return matchesQuery && matchesCategory;
  });
}

export function getLabCategories(): string[] {
  return [...new Set(STANDALONE_LABS.map(l => l.category))];
}
